# Generated by Django 3.2.3 on 2021-08-14 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_auto_20210727_2113'),
        ('customer', '0004_auto_20210814_1700'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='barber',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='public.barber'),
        ),
        migrations.AddField(
            model_name='order',
            name='barber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='public.barber'),
        ),
    ]
