# Generated by Django 3.2.3 on 2021-08-14 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_order_barber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalorder',
            name='order_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
