# Generated by Django 3.2.3 on 2021-08-14 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_auto_20210814_1940'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalorder',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='order',
            name='services',
        ),
    ]
