# Generated by Django 3.2.3 on 2021-08-14 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_auto_20210814_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='at_finish',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='historicalorder',
            name='et_finish',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='at_finish',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='et_finish',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
