# Generated by Django 3.2.3 on 2021-08-14 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_auto_20210814_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalorder',
            name='et_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='et_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
