# Generated by Django 3.2.3 on 2021-07-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
