# Generated by Django 3.2.3 on 2021-07-25 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mainshop',
            options={'verbose_name_plural': 'MainShops'},
        ),
        migrations.AlterModelOptions(
            name='shopbranch',
            options={'verbose_name_plural': 'ShopBranches'},
        ),
        migrations.AlterField(
            model_name='historicalmainshop',
            name='subscription',
            field=models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Full Access', 'Full Access')], max_length=25),
        ),
        migrations.AlterField(
            model_name='historicalshopbranch',
            name='closing_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalshopbranch',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalshopbranch',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='historicalshopbranch',
            name='opening_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='mainshop',
            name='main_branch',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop_branch', to='shopadmin.shopbranch'),
        ),
        migrations.AlterField(
            model_name='mainshop',
            name='subscription',
            field=models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Full Access', 'Full Access')], max_length=25),
        ),
        migrations.AlterField(
            model_name='shopbranch',
            name='closing_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shopbranch',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='shopbranch',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='shopbranch',
            name='opening_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shopsubscription',
            name='subscription_type',
            field=models.CharField(choices=[('Free', 'Free'), ('Basic', 'Basic'), ('Gold', 'Gold'), ('Platinum', 'Platinum'), ('Diamond', 'Diamond'), ('Full Access', 'Full Access')], max_length=25),
        ),
    ]
