# Generated by Django 3.2.3 on 2021-07-25 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0002_auto_20210725_1201'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmainshop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mainshop',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
