# Generated by Django 3.2.3 on 2021-07-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0003_auto_20210725_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalmainshop',
            name='main_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mainshop',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='mainshop_images'),
        ),
    ]
