# Generated by Django 3.2.3 on 2021-07-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0004_auto_20210725_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalmainshop',
            name='main_image',
        ),
        migrations.RemoveField(
            model_name='mainshop',
            name='main_image',
        ),
    ]
