# Generated by Django 3.2.3 on 2021-07-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0006_auto_20210725_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshopbranch',
            name='main_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shopbranch',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='shops/'),
        ),
    ]
