# Generated by Django 3.2.3 on 2021-07-27 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0007_auto_20210726_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalshopbranch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='shopbranch',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
