# Generated by Django 3.2.3 on 2021-07-30 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0008_auto_20210727_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalsubservice',
            name='shops',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='shopadmin.shopbranch'),
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='shops',
        ),
        migrations.AddField(
            model_name='subservice',
            name='shops',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shopadmin.shopbranch'),
        ),
    ]
