# Generated by Django 3.2.3 on 2021-08-12 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0011_historicaloffering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsubservice',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='subservice',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
