# Generated by Django 3.2.3 on 2021-08-12 09:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0012_auto_20210812_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloffering',
            name='offer_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='historicaloffering',
            name='time_added',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offering',
            name='offer_code',
            field=models.CharField(blank=True, max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='offering',
            name='subservices',
            field=models.ManyToManyField(blank=True, to='shopadmin.SubService'),
        ),
        migrations.AddField(
            model_name='offering',
            name='time_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offering',
            name='shops',
            field=models.ManyToManyField(blank=True, to='shopadmin.ShopBranch'),
        ),
    ]
