# Generated by Django 3.2.3 on 2021-08-12 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopadmin', '0013_auto_20210812_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaloffering',
            name='special_offer',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name='offering',
            name='special_offer',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
